=== D4ryus/studium/sem_06/it_praktikum_02/sml.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT Saison (Beginn, Ende, Mannschaften+, Spiel+)>
        <!ATTLIST Saison typ (Euro|Champions) #IMPLIED>
<!ELEMENT Mannschaften (Name, Land, Trainer, Spieler+, Erfolge*)>
        <!ATTLIST Mannschaften id ID #REQUIRED>

<!ELEMENT Spiel EMPTY>
        <!ATTLIST Spiel heim IDREF #REQUIRED>
        <!ATTLIST Spiel gast IDREF #REQUIRED>
        <!ATTLIST Spiel ergebnis CDATA #IMPLIED>
<!ELEMENT Spieler (#PCDATA)>
        <!ATTLIST Spieler position (Torwart|Verteidiger|Mittelfeld|StÃ¼rmer) #REQUIRED>
<!ELEMENT Erfolge (#PCDATA|Jahr|Titel)*>
<!ELEMENT Beginn (#PCDATA)>
<!ELEMENT Ende (#PCDATA)>
<!ELEMENT Titel (#PCDATA)>
<!ELEMENT Jahr (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Land (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>

=== D4ryus/studium/sem_06/it_praktikum_02/sml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Saison SYSTEM "sml.dtd">
<Saison typ="Euro">
  <Beginn>10.10.2014</Beginn>
  <Ende>0.10.2015</Ende>
  <Mannschaften id="asdf">
    <Name>somename</Name>
    <Land>deutschland</Land>
    <Trainer>peter</Trainer>
    <Spieler position="Torwart">Hans</Spieler>
    <Spieler position="Verteidiger">Georg</Spieler>
    <Spieler position="Mittelfeld">Sepp</Spieler>
    <Spieler position="Stürmer">Chris</Spieler>
    <Erfolge>Gewonn die <Titel>SuperLeague</Titel> im Jahr <Jahr>1991</Jahr>.</Erfolge>
    <Erfolge>Gewonn die <Titel>SuperSuperLeague</Titel> im Jahr <Jahr>1992</Jahr>.</Erfolge>
  </Mannschaften>
  <Mannschaften id="fdsa">
    <Name>someothername</Name>
    <Land>deutschland</Land>
    <Trainer>hand</Trainer>
    <Spieler position="Torwart">Hans</Spieler>
    <Spieler position="Verteidiger">Georg</Spieler>
    <Spieler position="Mittelfeld">Sepp</Spieler>
    <Spieler position="Stürmer">Chris</Spieler>
    <Erfolge>Gewonn die <Titel>SuperSuperLeague</Titel> im Jahr <Jahr>1991</Jahr>.</Erfolge>
    <Erfolge>Gewonn die <Titel>SuperLeague</Titel> im Jahr <Jahr>1992</Jahr>.</Erfolge>
  </Mannschaften>
  <Spiel heim="asdf" gast="fdsa" ergebnis="5:3"></Spiel>
</Saison>
