=== D4ryus/studium/sem_06/it_praktikum_02/vorlesung_1.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT Vorlesung (Titel, Hochschule+, SWS, Semester, Kapitel+, Quelle+)>
        <!ELEMENT Titel (#PCDATA)>
        <!ELEMENT Hochschule (#PCDATA)>
        <!ELEMENT SWS (#PCDATA)>
        <!ELEMENT Semester (#PCDATA)>
        <!ELEMENT Kapitel (Name, Termin+)>
                <!ATTLIST Kapitel bewertung CDATA "1">
                <!ATTLIST Kapitel nummer CDATA #REQUIRED>
                <!ATTLIST Kapitel quelle IDREF #IMPLIED>
        <!ELEMENT Quelle (Author+, Titel)>
                <!ATTLIST Quelle id ID #REQUIRED>
                <!ATTLIST Quelle type (Monographie|Artikel|Dissertation|Abschlussarbeit) #REQUIRED>
        <!ELEMENT Author (#PCDATA)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Termin (#PCDATA)>

=== D4ryus/studium/sem_06/it_praktikum_02/vorlesung_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Vorlesung SYSTEM "vorlesung_1.dtd">
<Vorlesung>
  <Titel>Seminar</Titel>
  <Hochschule>HAW Landshut</Hochschule>
  <SWS>4</SWS>
  <Semester>Sommersemester</Semester>
  <?myTool align = left ?>
  <Kapitel nummer="1" bewertung="2"> </Kapitel>
  <Kapitel nummer="2" bewertung="2" quelle="Q1"> </Kapitel>
  <Quelle id="Q1" type="Monographie"></Quelle>
</Vorlesung>
