=== D4ryus/studium/sem_06/it_praktikum_02/vorlesung_0.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT Vorlesung (Titel, Semester+, Hochschule, SWS, Kapitel+, Quelle*)>
        <!ELEMENT Titel (#PCDATA)>
        <!ELEMENT Semester (#PCDATA)>
        <!ELEMENT Hochschule (#PCDATA)>
        <!ELEMENT SWS (#PCDATA)>
        <!ELEMENT Kapitel (#PCDATA)>
                <!ATTLIST Kapitel nummer CDATA #REQUIRED>
                <!ATTLIST Kapitel quelle IDREF #IMPLIED>
        <!ELEMENT Quelle (Autor+, Titel)>
                <!ATTLIST Quell quelleID ID #REQUIRED>

=== D4ryus/studium/sem_06/it_praktikum_02/vorlesung_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Vorlesung SYSTEM "vorlesung_0.dtd">
<Vorlesung>
  <Titel>Seminar</Titel>
  <Semester>Sommersemester</Semester>
  <Hochschule>HAW Landshut</Hochschule>
  <SWS>4</SWS>
  <?myTool align = left ?>
  <Kapitel nummer="1">Einf√ºhrung </Kapitel>
  <Kapitel nummer="2" quelle="Q1">Grundlagen von Netzwerk</Kapitel>
  <Quelle quelleID="Q1">
    <Author>someone</Author>
    <Titel>Lehrbuch 1.23</Titel>
  </Quelle>
</Vorlesung>
