=== D4ryus/studium/sem_06/it_praktikum_03/bpml.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ENTITY at "@">
<!NOTATION JPG PUBLIC "JPG 1.0">
<!NOTATION GIF PUBLIC "GIF 1.0">
<!ENTITY genjpg SYSTEM "genjpg.jpg" NDATA JPG>
<!ENTITY gengif SYSTEM "genjpg.gif" NDATA GIF>
<!ENTITY StringElem "(#PCDATA)">
<!ENTITY StringAttr "CDATA">

<!ELEMENT Preisübersicht (Tankstelle+, Pächter+, Mineralölgesellschaft*, Option?)>
        <!ATTLIST Preisübersicht datum CDATA #REQUIRED>

<!ELEMENT Tankstelle (Name, Adresse, Geodaten, Beschreibung*, Preis*)>
        <!ATTLIST Tankstelle pid IDREF #REQUIRED>
        <!ATTLIST Tankstelle mid IDREF #REQUIRED>
        <!ATTLIST Tankstelle rating (1|2|3|4|5|6) #IMPLIED>
        <!ATTLIST Tankstelle pic CDATA #IMPLIED>

<!ELEMENT Preis (#PCDATA)>
        <!ATTLIST Preis Kraftstoffart (E10|Super|Diesel|SuperPlus) #REQUIRED>

<!ELEMENT Mineralölgesellschaft (Name, Adresse, Email)>

<!ELEMENT Option ANY>
<!ELEMENT Geodaten (Länge, Breite)>
<!ELEMENT Pächter (Name, Adresse)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Adresse (#PCDATA)>
<!ELEMENT Länge (#PCDATA)>
<!ELEMENT Breite (#PCDATA)>
<!ELEMENT Beschreibung (#PCDATA)>

=== D4ryus/studium/sem_06/it_praktikum_03/bpml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Preisübersicht SYSTEM "bpml.dtd">
<Preisübersicht datum="12.12.12">
  <Tankstelle pid="id1" mid="id2" rating="5">
    <Name>T1</Name>
    <Adresse>A1</Adresse>
    <Geodaten>
      <Länge>123</Länge>
      <Breite>321</Breite>
    </Geodaten>
    <Beschreibung>asdf</Beschreibung>
    <Preis Kraftstoffart="Diesel">80.00</Preis>
    <Preis Kraftstoffart="E10">100.00</Preis>
    <Preis Kraftstoffart="Super">110.00</Preis>
    <Preis Kraftstoffart="SuperPlus">120.00</Preis>
  </Tankstelle>
  <Pächter>
    <Name>Hans</Name>
    <Adresse>A2</Adresse>
  </Pächter>
  <Mineralölgesellschaft>
    <Name>M1</Name>
    <Adresse>str3</Adresse>
    <Email>something@anotherthing.net</Email>
  </Mineralölgesellschaft>
  <Option>none</Option>
</Preisübersicht>
